# 인터페이스 개발 #8 (2021.01.08)



## 예외처리 (except)



### 1. 내용

* 우리 코드 내에서 예상할 수 없는 오류들이 발생했을 때 사용
* 데이터베이스에 연결하려고 했는데, 데이터베이스 꺼져 있을 때 오류 나오기 때문에 사용
* 내부 프로그램 논리적인 오류는 없는데 외부 resource 연결에서 오류 나올 때 사용

```python
def my_func(list_data):
    my_sum = 0
    try :      # ==> error가 발생할 수 있을 만한 구간 위에
        my_sum = list_data[0] + list_data[1] + list_data[2]
    except Exception as err :  # ==> Exception 모든 에러를 다 지칭함
        print('실행시 문제가 발생했어요!')
        my_sum  = 0
        # 모든 에러를 위 코드와 같이 예외 처리 하겠다.
    else :     # ==> 문제 없다면 try 밑에꺼 그대로 실행
        print('실행시 문제가 없어요')
    finally :
        print('만약 finally가 존재하면 이 부분은 무조건 실행돼요.')
    
    return my_sum

my_list = [1,2]
print(my_func(my_list))
```
